sudo: required
language: node_js
node_js:
  - "node"

services:
  - docker

before_install:
- ls
- docker build -t ci-bm .
- docker run -d -p 8080:8080 --name app ci-bm
- docker ps -a

script:
- docker exec app /usr/bin/echo hello

after_script:
- docker rm -f app
